### ISSUE TITLE
Fix Issues in Safari

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum-frontend#72]

**Comment by likt0r** [comment]
```[tasklist]
### Tasks
- [ ] Fix Footer Issue
- [ ] Check Claim Submission
- [ ] Check Article Swiping
```

**Comment by likt0r** [comment]
Double content in Footer

![Image](https://github.com/faktenforum/faktenforum-frontend/assets/12658568/ead18378-eb7f-48f4-8b21-c65caf804f14)

**Comment by stephanmax** [comment]
- Cannot replicate double content issue on Safari 17.2 @ macOS Monterey.
- Swiping of the latest news on the main page and claim submission looks good on iOS (iPhone 12 mini) except for two minor layout hiccups (see screenshots attached): we get a horizontal scroll bar on the homepage and some of the headlines on the claim page are hard to read
![Bildschirmfoto 2024-01-12 um 11 54 53](https://github.com/faktenforum/faktenforum-frontend/assets/334191/848d6c1c-827b-4a8d-b898-70faecf53497)
![Bildschirmfoto 2024-01-12 um 11 53 46](https://github.com/faktenforum/faktenforum-frontend/assets/334191/9566dd58-b5ba-41b6-93f4-1f60b84eb72e)
