### ISSUE TITLE
Update Styling of About NoFake News Cards

### ISSUE THREAD

**Issue by likt0r** [faktenforum/faktenforum-frontend#73]
```[tasklist]
### Tasks
- [x] Show Image source on hover in Image
- [x] Restyle more Buttons
- [ ] Disable Text ellipsis in Title
```

**For local development, you have to add the following variable to your local .env file**

**NUXT_PRIVATE_NO_FAKE_NEWS_URL="https://docs.google.com/spreadsheets/d/1lGnt5u7qmeO9ZtxlxlkMtdGqmNQPKR4VGi2HlsoB_ik/gviz/tq"**
